# References

1. Intro to Tensors:<br>https://www.tensorflow.org/guide/tensor/
2. Broadcasting in TensorFlow:<br>https://www.tensorflow.org/api_docs/python/tf/broadcast_to

# Necessary imports

In [3]:
import tensorflow as tf # For accessing TensorFlow library
import numpy as np # For accessing NumPy library

# Definition

Tensors are **immutable null-dimensional, one-dimensional or multi-dimensional arrays** with a uniform type (the data type is given in the field **dtype**).

# Basic terms

**Axis / Dimension**: A separate sequence among a sequence of sequences.<br>
**Shape**: The tuple containing the number of elements in each axis of the tensor. <br>
**Rank**: Number of axes a tensor has. So, scalar => rank 0, vector => rank 1, matrix => rank 2...<br>
**Size**: Total size of the vector i.e. product of the shape vector.

Axes are generally defined for batches, the sample data set and the features of the data set (i.e. potential predictors of a certain variable). Sample data sets are 2-dimensional, having axes for width and height. Hence, a typical tensor would be of rank 4.

# CREATION METHOD 1: Converting non-tensor objects

We can use any Python object shaped liked tensors ex. homogenous lists and tuples, arrays or matrices, and convert them to tensor objects. Even single-valued constants can be converted to tensor objects. Many functions in the TensorFlow library automatically convert such objects to tensor objects, but many also accept only tensor objects as arguments, requiring an explicit conversion.

In [27]:
tensor1 = tf.convert_to_tensor(1)
tensor2 = tf.convert_to_tensor([1, 2, 3])
tensor3 = tf.convert_to_tensor(np.matrix([[1, 2, 3], [3, 4, 5]]))

print("\ntensor1:", tensor1)
print("\ntensor2:", tensor2)
print("\ntensor3:", tensor3)


tensor1: tf.Tensor(1, shape=(), dtype=int32)

tensor2: tf.Tensor([1 2 3], shape=(3,), dtype=int32)

tensor3: tf.Tensor(
[[1 2 3]
 [3 4 5]], shape=(2, 3), dtype=int64)


# CREATION METHOD 2: Defining a constant tensor

The function 'constant' creates a constant tensor object. The data types of the elements can be numerical or non-numerical. However, the data type should be the same for all elements. If the **dtype** field is not given, the function will simply consider the data type of the element with the most general data type as its **dtype** i.e. the data type that can represent all the data. For example, if float and integer values are given for a single tensor, the **dtype** will be float, or more specifically, float32.

# Tensor ranks

In [98]:
print(tf.constant(2))
# A constant tensor with one element, and data type 'int32'.
# Dimensions (i.e. shape) are empty as it is one integer.
# This is a scalar tensor, or rank 0 tensor i.e. tensor with no axes.

tf.Tensor(2, shape=(), dtype=int32)


In [25]:
print(tf.constant([1, 2, 3, 4]))
# This is a constant tensor with 4 elements, and data type 'int32'.
# Dimensions (i.e. shape) are 4 rows and 0 columns.
# This is a vector tensor, or rank 1 tensor i.e. tensor with one axis.

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [40]:
print(tf.constant([[1, 2.4, 3, 4], [-1, -2.6, -3, -4]]))
# This is a constant tensor with 8 elements, and data type 'float32'.
# Dimensions (i.e. shape) are 2 rows and 4 columns.
# This is a matrix tensor, or rank 2 tensor i.e. tensor with two axes.

tf.Tensor(
[[ 1.   2.4  3.   4. ]
 [-1.  -2.6 -3.  -4. ]], shape=(2, 4), dtype=float32)


Instead of giving lists, we can give any numerical data type or sequential data type, such tuples, arrays, matrices, etc.

In [34]:
# Demonstrating constant tensor construction using matrix...
print(tf.constant(np.matrix([[1, 2, 3], [1, 2, 4]])))

tf.Tensor(
[[1 2 3]
 [1 2 4]], shape=(2, 3), dtype=int64)


**NOTE 1**: Tensors can have more axes than two. Hence, there can be tensors of rank 3, rank 4, etc..<br>
**NOTE 2**: You can specify the data type through the argument 'dtype', as in **tf.constant(x, dtype = int32)**

# Tensor attributes

In [41]:
# Consider the following tensor...
myTensor = tf.constant([[1, 2], [3, 4]])
print("\nSimply printing the tensor...")
print(myTensor)
print("\nData type of the tensor...")
print(myTensor.dtype)
print("\nShape of the tensor...")
print(myTensor.shape)
print("\nRank of the tensor...")
print(tf.rank(myTensor)) # Number of dimensions (is 2 for any matrix)
print("\nSize of the tensor...")
print(tf.size(myTensor)) # Number of elements (3x3 = 9)


Simply printing the tensor...
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)

Data type of the tensor...
<dtype: 'int32'>

Shape of the tensor...
(2, 2)

Rank of the tensor...
tf.Tensor(2, shape=(), dtype=int32)

Size of the tensor...
tf.Tensor(4, shape=(), dtype=int32)


**NOTE**: The rank and size functions return tensor objects containing the required values. To obtain single values, we must use the '.numpy' method, (as discussed in the 'Converting tensors to NumPy n-dimensional arrays' subsection in the 'Operations' section)

# Indexing

In [14]:
# Consider the following tensor...
myTensor = tf.constant(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ])

## Simple indexing

In [15]:
# Row indexing
print("\nPrinting each row...")
for i in range(0, 3): print(myTensor[i])
    
# Column indexing
print("\nPrinting each column...")
for i in range(0, 3): print(myTensor[:, i])

# Element indexing
print("\nPrinting each element...")
for i in range(0, 3):
    for j in range(0, 3):
        print(myTensor[i, j])


Printing each row...
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)
tf.Tensor([7 8 9], shape=(3,), dtype=int32)

Printing each column...
tf.Tensor([1 4 7], shape=(3,), dtype=int32)
tf.Tensor([2 5 8], shape=(3,), dtype=int32)
tf.Tensor([3 6 9], shape=(3,), dtype=int32)

Printing each element...
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


**NOTE**: Doing something like **for t in myTensor: print(t)** will print all the rows. Hence, you can say that each element of a tensor is represented by a row, which can itself have mutliple elements.

## Slicing

In [16]:
# Slicing
print("\nLast two elements of the first row...")
print(myTensor[0, 1:3])
print("\nBottom left four elements...")
print(myTensor[0:3, 1:3])


Last two elements of the first row...
tf.Tensor([2 3], shape=(2,), dtype=int32)

Bottom left four elements...
tf.Tensor(
[[2 3]
 [5 6]
 [8 9]], shape=(3, 2), dtype=int32)


## Negative indexing

In [17]:
print("\nLast row...")
print(myTensor[-1])
print("\nLast column...")
print(myTensor[:, -1])
print("\nLast element...")
print(myTensor[-1, -1])


Last row...
tf.Tensor([7 8 9], shape=(3,), dtype=int32)

Last column...
tf.Tensor([3 6 9], shape=(3,), dtype=int32)

Last element...
tf.Tensor(9, shape=(), dtype=int32)


# Functions

## Typecasting

You can convert the data type (dtype) of the values of your tensor through the TensorFlow function **cast**. Note that applying this function will create a new tensor, not alter the original tensor.

In [123]:
tensor1 = tf.constant(2.3, dtype = tf.float32)
tensor2 = tf.cast(myTensor, dtype = tf.int32)
print(tensor2)

tf.Tensor(2, shape=(), dtype=int32)


## Converting tensors to NumPy n-dimensional arrays

For doing this, we use the '.numpy' function, which returns a separate NumPy array.

In [31]:
myTensor = tf.constant(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ])
print("\nFull tensor...")
print(myTensor.numpy())
print("\nFirst row...")
print(myTensor[0].numpy())
print("\nFirst column...")
print(myTensor[:, 0].numpy())
print("\nFirst element...")
print(myTensor[0, 0].numpy())


Full tensor...
[[1 2 3]
 [4 5 6]
 [7 8 9]]

First row...
[1 2 3]

First column...
[1 4 7]

First element...
1


In [32]:
# Confirming the return type of the .numpy function...
print(type(myTensor.numpy()))

<class 'numpy.ndarray'>


Using this function, we can obtain the rank and size of a tensor as a proper value (instead of a tensor object, which is the usual output of the TensorFlow functions **rank** and **size**.

In [38]:
print("Rank:", tf.rank(myTensor).numpy()) # Number of dimensions (is 2 for any matrix)
print("Size:", tf.size(myTensor).numpy()) # Number of elements (3x3 = 9)

Rank: 2
Size: 9


## Reshaping

You can efficiently change the shape of the tensor using the TensorFlow function **reshape**.

In [140]:
tensor1 = tf.constant([1, 2, 3, 4])
tensor2 = tf.reshape(tensor1, (2, 2))
tensor3 = tf.reshape(tensor2, (4, 1))
# 1st argument => tensor to be reshaped
# 2nd argument => shape sequence (list, tuple or vector)
print("\ntensor1...")
print(tensor1)
print("\ntensor2...")
print(tensor2)
print("\ntensor3...")
print(tensor3)


tensor1...
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)

tensor2...
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)

tensor3...
tf.Tensor(
[[1]
 [2]
 [3]
 [4]], shape=(4, 1), dtype=int32)


## Broadcasting

Broadcasting is the process of making the shapes of arrays compatible for arithmetic operations. Two shapes are compatible if for each dimension pair they are either equal or one of them is one. In broadcasting, the smaller array is transformed appropriately according to larger array (i.e. the smaller array is broadcasted to the larger array) such that the arithmetic operations can be performed on these arrays. This process happens automatically under the right conditions (discussed below). This can also be done deliberately, as we will see here...

In [21]:
tensor1 = tf.constant([1, 2, 3])
tensor2 = tf.broadcast_to(tensor1, [3, 3]) # 2 rows, 3 columns
tensor3 = tf.broadcast_to(tensor1, [3, 3]) # 3 rows, 3 columns

In [20]:
print("\ntensor1:", tensor1)
print("\ntensor2:", tensor2)
print("\ntensor3:", tensor3)


tensor1: tf.Tensor([1 2 3], shape=(3,), dtype=int32)

tensor2: tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)

tensor3: tf.Tensor(
[[1 2 3]
 [1 2 3]
 [1 2 3]], shape=(3, 3), dtype=int32)


Here, the TensorFlow function **broadcast_to** transforms and replicates the original data structure within the tensor based on the given dimensions. But it does not allow truncation of the original data, hence reshaping into a dimension is only possible if the original data can be replicated completely. Note that this function creates a new persistent tensor object, not just a temporary result.

**Note on automatic broadcasting**<br>
Operating on tensors can result in automatic broadcasting. The matrix addition of tensor containing matrix M to tensor containing matrix N will broadcast the result if the result of the M is one of the following:
1. Single-valued constant
2. Has same number of columns as N, and perfectly divides the number of rows in N
3. Has same number of rows as N, and perfectly divides the number of columns in N

# Topics not covered

1. Operations on tensors
2. Ragged tensors
3. Sparse tensors