# References

1. Intro to variables (in TensorFlow):<br>https://www.tensorflow.org/guide/variable
2. Mastering TensorFlow Variables:<br>https://towardsdatascience.com/mastering-tensorflow-variables-in-5-easy-step-5ba8062a1756
3. Trainable vs. non-trainable variables:<br>https://stackoverflow.com/questions/48460057/what-does-it-mean-that-a-tf-variable-is-trainable-in-tensorflow

# Necessary imports

In [1]:
import tensorflow as tf # For accessing TensorFlow library
import numpy as np # For accessing NumPy library

# Definition

Variables in TensorFlow are **mutable null-dimensional, one-dimensional or multi-dimensional arrays** with a uniform type (the data type is given in the field **dtype**). It is the preferred object type for representing a shared and persistent state that you can manipulate with any operation, including TensorFlow models.
<br><br>
**_Tensors vs. Variables_**
<br>
The most important difference between Variables and Tensors is mutability i.e. values of a 'Variable' object can be updated. Unlike Tensors, Variables cannot be reshaped. You can apply the TensorFlow function **reshape** on Variables, but it will create a new Tensor with the given shape, and not reshape the Variable itself. Note that Variables can be converted to Tensors using the **convert_to_tensor** function found in the TensorFlowLibrary. 
<br><br>
**_Need for Variables_**
<br>
Variable objects are mainly used to store model parameters. Since model parameter values keep updating during training, we can only use Variables, and not Tensors.

- **Shared**: visible to other parts of the program
- **Persistent**: given dedicated memory space
- **State (of an entity)**: the set of values defining the nature of the entity's existence
- **Manipulation (of state)**: Any update in a value or parameter regarding an entity
- **Entity**: any definable and existing unit ex. trained model

# Creation

We can instantiate (i.e., create) Variable objects with the TensorFlow function **Variable**. This function accepts different data types as parameter such as integers, floats, strings, lists, and 'Constant' (which can be created through the TensorFlow function **constant**). objects.

In [38]:
var1 = tf.Variable([1, 2, 3])
var2 = tf.Variable(["abc", "def", "ghi"])
var3 = tf.Variable(np.array([[1, 2, 3], [4, 5, 6]]))
var4 = tf.Variable(tf.constant([1, 2, 3]))

# Printing the different variable objects
for var in [var1, var2, var3, var4]: print(var, "\n------------")

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)> 
------------
<tf.Variable 'Variable:0' shape=(3,) dtype=string, numpy=array([b'abc', b'def', b'ghi'], dtype=object)> 
------------
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6]])> 
------------
<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)> 
------------


**NOTE**: Every Variable must specify an initial value. Otherwise, TensorFlow raises the error _"Value Error: initial_value must be specified"_. Therefore, make sure that you pass on an initial value argument when creating Variable objects.

## Trainable vs. non-trainable variables

Trainable variables are those variables which optimizer functions (which optimize models, which may include variables to store their states) can act upon. Note that both trainable variables and non-trainable variables are mutable. A variable can be defined as trainable or non-trainable by giving the **trainable** argument in the TensorFlow function **Variable** (the variable class constructor) as either True or False. You can set the trainability of variables on and off for any reason, ex. for freezing layers and variables during fine-tuning.
<br><br>
When a variable is defined as 'trainable', it is added to the collection **GraphKeys.TRAINABLE_VARIABLES**. During training, an optimizer gets the content of this collection of trainable variables through the TensorFlow function **trainable_variables** and applies the training process to all these variables.
<br><br>
The typical example of a non-trainable variable is **global_step**, because its value does change over time (+1 for each training iteration, usually), but you would not want to apply an optimization algorithm to it.

## Converting Variables to Tensors and Numpy n-dimensional arrays

To be able to view a Variable’s values, we can use the **.value( )** function (which returns a Tensor constructed using the Variable) as well as the **.numpy( )** function (which returns a NumPy n-dimensional array).

In [39]:
print("\nResult of '.value()' function...")
print(var1.value())
print("\nResult of '.numpy()' function...")
print(var1.numpy())


Result of '.value()' function...
tf.Tensor([1 2 3], shape=(3,), dtype=int32)

Result of '.numpy()' function...
[1 2 3]


# Lifecycle & naming

## Lifecycle

In TensorFlow, a Variable instance has the same lifecycle as other Python objects. When there are no references to a variable, it is automatically deallocated.

## Naming

Variables can also be named, using the 'name' argument in the TensorFlow function **Variable**. This feature can help you track and debug them. You can give two variables the same name. Variable names are preserved when saving and loading models. By default, variables in models will acquire unique variable names automatically, but they can also be specifically defined by the programmer.

# Topics not covered

1. Operations on variables
2. Functions on variables (not discussed due to similarity to Tensors)
3. Placing variables and tensors

**SHORT NOTE ON PLACING VARIABLES AND TENSORS**:
<br>
For better performance, TensorFlow will attempt to place tensors and variables on the fastest device compatible with its dtype. This means most variables are placed on a GPU, if one is available.
<br><br>
However, you can override this. In this snippet, place a float tensor and a variable on the CPU, even if a GPU is available. By turning on device placement logging, you can see where the variable is placed. However, although manual placement works, using distribution strategies can be a more convenient and scalable way to optimize your computation.